# Generated by Django 4.2.6 on 2024-02-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='ppic',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images/'),
        ),
    ]
