# Generated by Django 4.2.6 on 2024-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_ppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='ppic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
